### ISSUE TITLE
Highlight partial word selection

### ISSUE THREAD

**Issue by sabrogden** [sergey-su/logjoint#10]
By default, you have to select the entire word for other instances of the selection to be selected.  I don't like this and would like any instance of the selection to be highlighted regardless if the entire word is selected.  This is how vscode and notepad++ works, visual studio is between these.

In HighlightingManager.cs can wordSelection.IsWordBoundary checks be removed or have some way to turn this off.

scott

**Comment by sergey-su** [comment]
Agree. I'll fix it.

**Comment by sabrogden** [comment]
sweet, thanks, I see the change.

**Comment by sergey-su** [comment]
Update for windows is published.
