### ISSUE TITLE
Don't require DateTime.ParseExact

### ISSUE THREAD

**Issue by sabrogden** [sergey-su/logjoint#12]
I'm trying to parse date times in the following example using the following JUST.  This works good but sometimes the milliseconds only has 2 values rather than the 3 the parse exact is expecting (second json line has this).  This is coming from some node.js app and can't really be changed.

The parse exact blows up and I haven't found any other date format strings that work.  What I would like is to just do a DateTime.Parse, sample below that does what I was wanting.  Or if there is a way to accomplish this with other format strings that works.

Sample JUST
> "d": "#customfunction(logjoint.model,LogJoint.Json.Functions.TO_DATETIME,#valueof($.timestamp),yyyy-MM-ddTHH:mm:ss.fffZ)"

Sample JSON
> {"message":"a","level":"info","timestamp":"2019-04-10T22:15:03.329Z"}
{"message":"b","level":"info","timestamp":"2019-04-10T22:15:03.32Z"}

A sample that works, we could make a new function or reuse this.  I'm sure you will have a more generic solution :)

> static private DateTime TO_DATETIME_Impl(string value, string format, CultureInfo culture, DateTimeStyles additionalFlags)
		{
			try
			{
                if (string.IsNullOrWhiteSpace(format))
                {
                    return DateTime.Parse(value, culture.DateTimeFormat, DateTimeStyles.AdjustToUniversal | additionalFlags);
                }
                else
                {
                    return DateTime.ParseExact(value, format, culture.DateTimeFormat, DateTimeStyles.AdjustToUniversal | additionalFlags);
                }
			}
			catch (FormatException e)
			{
				throw new FormatException(string.Format("Failed to parse DateTime value '{2}' of format '{1}'. {0}", e.Message, format, value));
			}
		}

**Comment by sergey-su** [comment]
Use `FFF` for milliseconds with no zero padding.
https://dotnetfiddle.net/j81xDn

**Comment by sabrogden** [comment]
danke
