### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0 in latest

### ISSUE THREAD

**Issue by sabrogden** [sergey-su/logjoint#13]
Back to trying the json Just parser to load json log files.  Seeing this with the latest installer using the sample json/regex/just from file:///C:/Users/sabro/AppData/Local/LogJoint/bin/help/HowJsonParsingWorks.htm

![image](https://user-images.githubusercontent.com/16867884/114323696-9f8cf180-9ae3-11eb-979b-7361665cbe24.png)

**Comment by sergey-su** [comment]
Thanks for reporting. I can reproduce that. Working on the fix.

**Comment by sergey-su** [comment]
Update with the fix has been pushed. When logjoint updates itself, the issue must be gone.

**Comment by sabrogden** [comment]
Thanks, verified it's working
