### ISSUE TITLE
Multiple Logs merging

### ISSUE THREAD

**Issue by rkapl123** [sergey-su/logjoint#14]
Hi Sergey!

First, thank you for this great log viewer, it's exactly what I was searching for and has a moderately complex configuration. And it worked quite quickly for my log4perl logfiles (I used log4net as template, but reverted to regex for the details).

Now I have a problem: I'd like to merge multiple logs from different programs (each has a different namepart, such as "processFiles.log" or "OREstarter.log") all within one folder. Additionally I'm daily rotating the logs (for 1 month back) into the same folder, the rotated files have a date prefix, like 20210420.processFiles.log for yesterdays log (todays logs have not prefix).

Now I'd like to merge all logs in that folder together to see any side-influences that some programs might have.
I've tried to use the "Watch this folder for parts of rotated log", but this gets only one program's logs (processFiles.log, why this was chosen is not exactly clear to me, maybe because I took it for testing my regexes). Besides it complains about a timestamp ordering problem in a different program's log where I can find a thread and display it in the search results view, but it won't show up in the main display.

When I open a single log file, it's correctly displayed side-by-side of the other logfiles (also the "watched folder" is a large, combined log), but here I can only select ONE logfile instead of all rotated ones.

What I'd need is something between the "watched folder" and the single log file, a "watched logfile pattern", to display/merge all logfiles of one program side-by-side with all others (also grouped together).
Is there currently a way to achieve something like this?

-regards,
Roland

**Comment by rkapl123** [comment]
Hi, just for completeness: I've also tried to use the name patterns (last step in the manage formats wizard), but this doesn't work with the "Watch this folder for parts of rotated log" method. Somehow it seems to only filter the files on the single logfile selection dialog. For a generally usable setup it would be great to also allow this pattern to influence the selected files in the "Watch this folder for parts of rotated log", then you could separate your named logs in the name patterns/manage formats wizard and have all files in one go.

As a final perfection, a "save settings" button that persists all the above setup log collections would help a lot as well (not to have to set up everything from scratch).

-regards,
Roland

**Comment by sergey-su** [comment]
The ability to specify a search pattern(s) for a folder is a great idea. Thank you Roland for suggesting. I'll implement that shortly.

The patterns that one has specified in the formats wizard can be set as a pre-filled default in the  "Watch this folder for parts of rotated log" dialog. 

For the persistence part, I think the recent logs dialog should suffice. You could open the same folder multiple times using different formats and patterns.  It'll add several entries into the recent logs history. Later you'll be able to select them (multi-selection is done by holding the Ctrl or Command ⌘ on mac), and reopen them all at once.

**Comment by sergey-su** [comment]
An update was published. When logjoint updates itself @rkapl123 please check if the feature works for you
![image](https://user-images.githubusercontent.com/29118443/116008684-119e2400-a616-11eb-9cec-aa2f5636fe4c.png)

**Comment by rkapl123** [comment]
Hi Sergey!

This is great, however I've observed following problems:

I've set up a log format for my log4perl based logfiles and successfully added a search pattern for processFiles.log (I only put *.log into the name pattern of the manage format wizard):
![image](https://user-images.githubusercontent.com/7430763/116060069-cde10400-a681-11eb-8451-b5ceb27fa096.png)

Now, wanted to add another search pattern for oreStarter.log, utilising the same log4perl log format from before (as all my logfiles follow the same pattern and end in *.log). I clicked "add", then selected the log4perl log format, selected "Watch this folder..." and entered "*orestarter.log" in the search patterns. Nothing was added and no error message displayed.
When I added a single file based on the new format, it works.

Now, I've tried to use 2 separate log formats having the name patterns (*processfiles.log and *orestarter.log) already entered in the name pattern of the manage format wizard. And this time it works, however it is also necessary to enter the same search pattern in the "add new log source" dialog again.

I found it a bit confusing that the search pattern is duplicated between the log format and the log itself. I can see that it would be convenient to have the ability to define a log format decoupled from the filename pattern, but if it only works that way then it's better to avoid a separate entry in the "add new log source" dialog and just add any file patterns already defined in the log format by default (and display them in brackets after the path in the overview pane!)
![image](https://user-images.githubusercontent.com/7430763/116065377-3ed6ea80-a687-11eb-9fc8-1094e4b54db7.png)

Also the timestamp ordering has problems without the search pattern entered in the "add new log source" dialog.

-regards,
Roland

**Comment by sergey-su** [comment]
Problem 1. Opening logs of one format matching different patterns. My idea was that one can specify multiple search patterns separating them by semicolon. 
![image](https://user-images.githubusercontent.com/29118443/116132900-5c7b7280-a6ce-11eb-9e47-905a5d347066.png)
This is what was implemented and published. Please try that.

However I see that it's totally not obvious from the UI. What you have tried - to open logs of the same format from the same folder using another pattern - makes sense. It did not work because the program thinks you're opening the thing that has already been open. Probably the tool should be smarter and factor in the filters. I'll fix that.

Problem 2. Pre-filling the search patterns from the format definition. That has not been implemented.  Sorry for not mentioning that. I just wanted an early confirmation from you that that approach works.

Problem 3.  "timestamp ordering". Please describe the steps to reproduce.

**Comment by rkapl123** [comment]
OK, so after defining a "generic" (without a name pattern in the manage format wizard),
![grafik](https://user-images.githubusercontent.com/7430763/116205046-a485ae00-a73d-11eb-8ae8-65f535970610.png)

I added a new log with a search pattern (which works) and then another - different search pattern - which doesn't work...
![grafik](https://user-images.githubusercontent.com/7430763/116207164-e0ba0e00-a73f-11eb-9f73-691094ec77b1.png)

When adding logs as you suggested
![grafik](https://user-images.githubusercontent.com/7430763/116207302-05ae8100-a740-11eb-9289-92bc724539aa.png)
there arises problem 3 (timestamp ordering), 
![grafik](https://user-images.githubusercontent.com/7430763/116207627-6047dd00-a740-11eb-993e-911a1bd4aea3.png)
which is reasonable, as there are usually same timestamps in different logs (they are written in parallel). However, when clicking "reorder log", nothing happens. 
When clicking "ignore", the box dissapears, but only one logfile pattern (*processfiles.log) remains, so *orestarter.log is ignored (you can't search/see anything). Even checking "fix order automatically" in the manage format wizard doesn't help in this case.

**Comment by sergey-su** [comment]
Of course, if you have two programs writing independent rotated logs, you should add them as two independent log sources even if they write in the same format.
Use multiple semicolon-separated search patterns only if you have to match differently named parts of a rotated log. However it's probably uncommon that a single pattern does not suffice.

Pushed an update that solves problems 1 and 2. Problem 3 is by-design.

**Comment by rkapl123** [comment]
Hi Sergey!
This makes sense now, I would just add an error message when trying to add a watched folder based on a log format that is already included.

regards,
Roland
