### ISSUE TITLE
CJK characters can not be displayed

### ISSUE THREAD

**Issue by jerrylususu** [sergey-su/logjoint#17]
Tried all fonts in the font selection menu. None of them can display CJK characters correctly.

![image](https://user-images.githubusercontent.com/17522475/134797602-5fa7d968-a5bc-48bc-9452-0b0c12eb05ae.png)

Test file: 
[9-50, 2021-9-26.txt](https://github.com/sergey-su/logjoint/files/7230894/9-50.2021-9-26.txt)

**Comment by sergey-su** [comment]
Thank you for the bug report.

Update's been published. The fix was to allow-list font nsimsun than now can be selected in the options:
![nsimsun](https://user-images.githubusercontent.com/29118443/134803613-d8a946e6-ffa0-4ffa-8acd-c54e2d7759d7.png)

Be sure to have specified in your format description that your logs are utf8 encoded. I used this for testing.
```
<format>
  <regular-grammar>
    <sample-log><![CDATA[9:50, 2021/9/26

测试
不能显示中文？22222
3333]]></sample-log>
    <head-re><![CDATA[^(?<date>\d{1,2}\:\d{1,2}\,\ \d{4}\/\d{1,2}\/\d{1,2})]]></head-re>
    <body-re><![CDATA[]]></body-re>
    <fields-config>
      <field name="Time"><![CDATA[TO_DATETIME(date, "m:s\\, yyyy\\/M\\/d")]]></field>
      <field name="Body"><![CDATA[body]]></field>
    </fields-config>
    <patterns />
    <encoding>utf-8</encoding>
  </regular-grammar>
  <id company="Neko Null" name="Log" />
  <description>
  </description>
</format>
```

**Comment by jerrylususu** [comment]
Thanks for your timely response! This is one of the fastest response I have ever had! But it seems that the update is not fully rolled out? I just checked for a new version but it says my current version is the newest one, which doesn't give more options in the font menu.

![image](https://user-images.githubusercontent.com/17522475/134804331-79753e90-0f60-407a-83e4-f1dd18ffa510.png)

**Comment by sergey-su** [comment]
Hm, that's strange. Did you get the original binaries by running the installer https://github.com/sergey-su/logjoint#downloads?

In any case try running the installer again. That will do what automatic update is supposed to do.

**Comment by jerrylususu** [comment]
Reinstalled with the installer, but still no new font selection. I guess I have to a complete uninstall and reinstall? But it seems Logjoint don't have an uninstaller... By the way, the executable file has a modification date just after your commit, so I think it should already be updated. I think there might be some issue on the different font names with regard to different region. Currently I am using Windows 10 with Simplified Chinese language, and if I search in my font folder, I can found `simsun.ttf` but not `nsimsun.ttf`.  

![image](https://user-images.githubusercontent.com/17522475/134815158-33d3f329-7e1f-44f9-9f3a-041219083af7.png)

**Comment by jerrylususu** [comment]
OK I found the problem. I tried to build a simple application in C# to check the code you used to determine available fonts, and it seems the font name is language specific. As I am running Windows in Simplified Chinese, some fonts returns Chinese name, including the font you chose for CJK (`nsimsum`, in Chinese `新宋体`). To fully solve the problem perhaps some language agnostic methods need to be used.

![image](https://user-images.githubusercontent.com/17522475/134816626-d8d9f8ec-317d-46d9-a16b-6bed086d2e09.png)

**Comment by sergey-su** [comment]
> if I search in my font folder, I can found simsun.ttf but not nsimsun.ttf
That must be it.

According to https://en.wikipedia.org/wiki/List_of_CJK_fonts nsimsun is monospace while simsun is not. logjoint really supports only monospace fonts. However simsun looks monospace too. simsun seems to work fine on my machine in logjoint.

May I ask you to try simsun locally before I allowlist it?
There must be settings file at
```
c:\Users\your_user_name\AppData\Roaming\LogJoint\e-E7FFECFD5A7308D0-global\x-10600E9CAFF5822B-settings
```
There you can enter any font-name. Logjoint will use it on next start. 
Let me know if simsun works without glitches - selection, search results highlighting.

**Comment by jerrylususu** [comment]
After I changed the file it seems LogJoint is broken... Nothing happens after I launch it (via start menu or double clicking on the executable file). No log or error message window.

**Comment by sergey-su** [comment]
Can you please try to print the values of GetName(0)?

```
FontFamily f = ...;
Console.WriteLine(f.GetName(0));
```

**Comment by jerrylususu** [comment]
Unfortunately it seems that's still language dependent. I've been trying to find some C# documentation on this `int32 language` parameter, but yielded no results. 

![image](https://user-images.githubusercontent.com/17522475/134817100-ed2941f2-e7a9-4557-802c-59aa847e25c8.png)

**Comment by sergey-su** [comment]
> After I changed the file it seems LogJoint is broken

Maybe xml markup got broken?

Deleting the file should help. The setting will be lost of course.

**Comment by jerrylususu** [comment]
Removed the xml setting file, yet it still fails to boot. I've checked taskmgr and there is no running process named `logjoint`.

Tried to launch Logjoint with task manager open. The process shows for a few seconds then disappears. No GUI is displayed.

![image](https://user-images.githubusercontent.com/17522475/134817180-a9b5f975-8590-4285-80cc-30d200fc067b.png)

Update: I tried to remove the whole logjoint folder in `AppData/Roaming`, which seems to fix the problem. Now I am able to launch Logjoint GUI.

**Comment by sergey-su** [comment]
Another try please:
GetName(0x007f)

See
https://docs.microsoft.com/en-us/windows/win32/intl/locale-invariant

**Comment by jerrylususu** [comment]
Sadly still no luck.

![image](https://user-images.githubusercontent.com/17522475/134817619-64ad634c-34af-4731-83c1-5b28613d4ff8.png)

**Comment by jerrylususu** [comment]
I am just fiddling around and it seems this fixes the problem. 

```csharp
var cu = new CultureInfo("en-US").LCID;

using(InstalledFontCollection col = new InstalledFontCollection()) {  
    foreach(FontFamily fa in col.Families) {  
        System.Console.WriteLine(fa.GetName(cu));
        
    }  
} 
```

![image](https://user-images.githubusercontent.com/17522475/134817818-feeac7e4-48b3-4be6-8bf7-b780747623cc.png)

**Comment by jerrylususu** [comment]
Regarding to the `simsun.ttf` problem, it seems that SimSun and NSimSun share the same ttf file. They both share the CJK character glyphs, and the only difference is that Latin region in NSimSun is monospace while SimSun isn't. This might explain why there only exists `simsun.ttf` but not `nsimsun.ttf`.

![image](https://user-images.githubusercontent.com/17522475/134817920-e681c2af-92b7-4c17-a016-888b15f6eff9.png)

**Comment by sergey-su** [comment]
Thanks. I'll publish an update that looks up the fonts by english names.

**Comment by jerrylususu** [comment]
Thanks for your quick fix! Can't wait to see the next version.

**Comment by sergey-su** [comment]
Please try new version (About->Update status->check now).

**Comment by jerrylususu** [comment]
Installed a new version & restarted app. Sadly the font selection is still the same...

![image](https://user-images.githubusercontent.com/17522475/134818687-91d66986-79e2-42ce-9778-8fc079643b64.png)

**Comment by sergey-su** [comment]
Huh, ok.
Can you please verify that my method of getting the names works as expected?
`GetName(0x09)`

**Comment by sergey-su** [comment]
Note that I'm using a static method `FontFamily.Families` without creating an InstalledFontCollection. Not sure if it matters, but please test the `FontFamily.Families`.

**Comment by jerrylususu** [comment]
Sadly no. By the way, en-US has a code of 1033 at my side.
![image](https://user-images.githubusercontent.com/17522475/134818895-907defd9-b974-407f-b65b-b2d1768690ad.png)
![image](https://user-images.githubusercontent.com/17522475/134818945-7a08d0a7-b380-4f5f-ba43-06d501b5b00d.png)

**Comment by jerrylususu** [comment]
> Note that I'm using a static method `FontFamily.Families` without creating an InstalledFontCollection. Not sure if it matters, but please test the `FontFamily.Families`.

Still having the font name issue.

![image](https://user-images.githubusercontent.com/17522475/134818993-a257991d-2d98-48b3-9b09-e5aa2ecae109.png)

**Comment by sergey-su** [comment]
> en-US has a code of 1033 at my side 

Ok. I thought the -us sublanguage part was redundant, but apparently it's important.

Fixing more...

**Comment by sergey-su** [comment]
try now

**Comment by jerrylususu** [comment]
Working now! Thanks for your quick fixes!

![image](https://user-images.githubusercontent.com/17522475/134819575-fd8fe1b0-c82c-47c3-9f65-5035d3059a26.png)

**Comment by sergey-su** [comment]
Thank you for help! Having to boot up a Chinese win10 VM otherwise would be laborious.

**Comment by jerrylususu** [comment]
> Thank you for help! Having to boot up a Chinese win10 VM otherwise would be laborious.

You're welcome. Debugging language/region related issues are never easy. With this CJK issue solved, I believe the user base of Logjoint will grow larger. Thanks again for your amazing work and quick response!

**Comment by jerrylususu** [comment]
Just noting here, searching and highlighting works perfectly!

![image](https://user-images.githubusercontent.com/17522475/134820046-67b2173c-5a1b-4520-8743-3dfdb184166d.png)

**Comment by sergey-su** [comment]
Good to know.

I noticed that the bookmarks view does not show correctly.
![image](https://user-images.githubusercontent.com/29118443/134820821-a27e6d00-c359-4c53-85b8-a59230d0ffcd.png)

The fix would be to put the following option to logjoint.exe.config (located next to the binary)
```xml
...
<LogJoint.Properties.Settings>
  ...
  <setting name="MonospaceBookmarks" serializeAs="String">
        <value>1</value>
  </setting>
</LogJoint.Properties.Settings>
```

This setting has been sort of experimental and is not visible in the options dialog.

**Comment by ycyun** [comment]
can you add korean characters too?
in nsimsun, there is only chinese fonts, 
https://github.com/naver/nanumfont?tab=readme-ov-file
nanumgothiccoding can be a korean monospace code

**Comment by sergey-su** [comment]
Added nanumgothiccoding.

**Comment by ycyun** [comment]
Thanks for extreamly fast response lol :D
