### ISSUE TITLE
Doesn't show logs with custom parser

### ISSUE THREAD

**Issue by xnorpx** [sergey-su/logjoint#27]
Hi!

Writing a custom parser for my loglines but having issues with the parser, everything tests successfully and it looks good.

But when opening the log it doesn't work.

![image](https://user-images.githubusercontent.com/302709/157783589-7180de50-d631-4e9a-a3f5-d045ec04601e.png)

![image](https://user-images.githubusercontent.com/302709/157783730-c27823d3-3dbe-4828-90cf-327967d5e0ce.png)

**Comment by xnorpx** [comment]
[parser.zip](https://github.com/sergey-su/logjoint/files/8228252/parser.zip)

**Comment by xnorpx** [comment]
Attached, xml file and example log

**Comment by sergey-su** [comment]
The sample contains an unexpected charachter  at the beginning of one line
![image](https://user-images.githubusercontent.com/29118443/157950708-d6fd517c-efbf-4a8e-a91c-4d1eff7695e6.png)

I fixed the format definition to tolerate such unexpected charachters. Also made a few changes to make the parsing less ambiguous and to tolerate small time ordering defects (apparently your logger does not guarantee 100% ordering by time). 
[format.zip](https://github.com/sergey-su/logjoint/files/8235225/format.zip)

**Comment by xnorpx** [comment]
Oh, my bad.

Thanks a lot! Verified it worked great now.
