### ISSUE TITLE
Is the web installer down? 

### ISSUE THREAD

**Issue by kevinliu23** [sergey-su/logjoint#41]
I keep getting a "underlying connection was closed" error when I try to install LogJoint. Can someone please take a look into the issue? Thank you!

**Comment by sergey-su** [comment]
Just tried. Worked for me. Does the problem persist for you?

**Comment by kevinliu23** [comment]
Yeah, I am still seeing the "underlying connection was closed" error. Maybe something wrong with my network but everything else seems to work.

**Comment by sergey-su** [comment]
To clarify, you're having a problem with Windows installer https://publogjoint.blob.core.windows.net/updates/logjoint.web.installer.exe ?

**Comment by kevinliu23** [comment]
Just tried it again with installer from the link you pasted and it seems to work this time! Thank you very much Sergey!
