### ISSUE TITLE
Feature Request: Option to Plot only Dot markers and remove throotling in that mode

### ISSUE THREAD

**Issue by pnelson786** [sergey-su/logjoint#8]
Can you support an option for plotting only Dot markers (no line plots)  and remove data throttling in that mode.
Changes are very simple (had to comment only few lines of code... I can share if needed) but do not know work with exposing options.

see image it very usable and helps find outliers easily
![image](https://user-images.githubusercontent.com/29609834/46548210-37f6eb00-c883-11e8-878c-6e823f268423.png)

Note: it would be good to cycle dotmarkers , in this mode like use cross for one , square for another but it is enchancement not critical,

**Comment by sergey-su** [comment]
Hi,
Sure, it's possible to add "no line" option for which the trolling threshold can be higher. Throttling can not be removed completely because view rendering time should be proportional to the size of the screen, not to the size of the input log that can be arbitrarily large.

**Comment by pnelson786** [comment]
Yes it is fine to reduce throothling threshold to 1 pixel in that mode (in case of performance issues), in line keep it as is 2 pixel. Is it possible to evaluate rendering time before hand and decide, in dot marker mode , it doesn't seems too shabby to plot markers the have the same x pixel location but different y pixel position. At least user does not miss outliers. Maybe while plotting markers prioritize plotting y values that differ the most( say 6 data share the same x pixel, plot min value and max value)

**Comment by sergey-su** [comment]
Added "Draw line" option: 

<img width="967" alt="screen shot 2018-10-08 at 21 07 32" src="https://user-images.githubusercontent.com/29118443/46628610-618f6b00-cb3e-11e8-92d3-dc4960e3ecc7.png">


Checkbox off

<img width="959" alt="screen shot 2018-10-08 at 21 07 47" src="https://user-images.githubusercontent.com/29118443/46628611-63f1c500-cb3e-11e8-9257-14d5339cf14e.png">


Additionally, no throttling would occur if limit of visible points is not exceeded for whole view. This means for small files there will be no throttling even if many points are concentrated in one place. For large files one can zoom to remove throttling, as before.

Changes pushed to master.

**Comment by pnelson786** [comment]
Thanks!
