### ISSUE TITLE
Filtering Rules gone in the latest

### ISSUE THREAD

**Issue by sabrogden** [sergey-su/logjoint#9]
I've been using a pretty old version of LogJoint and downloaded the latest version today to test some JSON formats and now the Filtering Rules tab is gone.  This was pretty much the entire reason I use LogJoint, filter out the nonsense and only view the lines I want.  Is there another way to accomplish this?

I can see it was removed on Commits on Aug 2, 2016, refactoring continues...

**Comment by sergey-su** [comment]
Yes, display filtering is gone. The feature created illusion that filtering works in constant time for any log which was true only for small logs fitting the memory. For large logs it was glitchy. 

Display filtering is replaced with search by filters. You define one or more filters here:
![image](https://user-images.githubusercontent.com/29118443/55669767-983f0780-587b-11e9-8d1f-0954b145b894.png)

Filters appear in the search suggestions list:
![image](https://user-images.githubusercontent.com/29118443/55669931-937b5300-587d-11e9-96b5-5c76f449309e.png)

When you select a filter and search by it, search results panel will contain the output while main log view in intact. Search results panel got few new features. It can display results from multiple searches merged. Results can be turned on or off. When you search by filter each positive rule in the filter gets own search result.  
![image](https://user-images.githubusercontent.com/29118443/55670079-2917e200-5880-11e9-8067-11cc5036533d.png)


I hope that search by filters is better than old display filters. Reasons:
1. Filters are persistent. Define once and recall them in search suggestions list after LogJoint restarts.
2. Search results panel can combine output of different filters and ad-hock searches.
3. Individual rules from a filter can also define highlighting color.
4. You locally-defined filters list can be exported and imported on another machine.

**Comment by sabrogden** [comment]
Thanks for the explanation.  First thought is i'm not sure about that, but I'll give it a try and see how it works for me.

I'm seeing the filter window chop off a little of the 3rd row and it's not resizable.  As i add more filters it's increasing in size but it's always short of showing all filters.

![image](https://user-images.githubusercontent.com/16867884/55752487-68237000-5a05-11e9-94e7-baa1a20df9b5.png)

scott
